spring.application.name=portal-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/psyche_portal}
spring.datasource.username=${DB_USERNAME:babikerbabiker}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



